version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command:
      npm run dev

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb://db:27017/moneeb # Updated to MongoDB connection string
    depends_on:
      - db

  db:
    image: mongo:5.0 # Using the MongoDB official image
    environment:
      MONGO_INITDB_DATABASE: moneeb # Optional: Set the initial database name
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db # MongoDB default data directory

volumes:
  db_data:
